// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Header.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Header.proto</summary>
public static partial class HeaderReflection {

  #region Descriptor
  /// <summary>File descriptor for Header.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static HeaderReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgxIZWFkZXIucHJvdG8aD3RpbWVzdGFtcC5wcm90byJFCgZIZWFkZXISEAoI",
          "ZnJhbWVfaWQYASABKAkSKQoFc3RhbXAYAiABKAsyGi5nb29nbGUucHJvdG9i",
          "dWYuVGltZXN0YW1wYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Header), global::Header.Parser, new[]{ "FrameId", "Stamp" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Header : pb::IMessage<Header> {
  private static readonly pb::MessageParser<Header> _parser = new pb::MessageParser<Header>(() => new Header());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Header> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HeaderReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Header() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Header(Header other) : this() {
    frameId_ = other.frameId_;
    Stamp = other.stamp_ != null ? other.Stamp.Clone() : null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Header Clone() {
    return new Header(this);
  }

  /// <summary>Field number for the "frame_id" field.</summary>
  public const int FrameIdFieldNumber = 1;
  private string frameId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string FrameId {
    get { return frameId_; }
    set {
      frameId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "stamp" field.</summary>
  public const int StampFieldNumber = 2;
  private global::Google.Protobuf.WellKnownTypes.Timestamp stamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Google.Protobuf.WellKnownTypes.Timestamp Stamp {
    get { return stamp_; }
    set {
      stamp_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Header);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Header other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (FrameId != other.FrameId) return false;
    if (!object.Equals(Stamp, other.Stamp)) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (FrameId.Length != 0) hash ^= FrameId.GetHashCode();
    if (stamp_ != null) hash ^= Stamp.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (FrameId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(FrameId);
    }
    if (stamp_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Stamp);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (FrameId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FrameId);
    }
    if (stamp_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Stamp);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Header other) {
    if (other == null) {
      return;
    }
    if (other.FrameId.Length != 0) {
      FrameId = other.FrameId;
    }
    if (other.stamp_ != null) {
      if (stamp_ == null) {
        stamp_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      Stamp.MergeFrom(other.Stamp);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          FrameId = input.ReadString();
          break;
        }
        case 18: {
          if (stamp_ == null) {
            stamp_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(stamp_);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
