// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PointCloud2.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PointCloud2.proto</summary>
public static partial class PointCloud2Reflection {

  #region Descriptor
  /// <summary>File descriptor for PointCloud2.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PointCloud2Reflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFQb2ludENsb3VkMi5wcm90bxoMSGVhZGVyLnByb3RvGhFQb2ludFhZWlJH",
          "Qi5wcm90byJECgtQb2ludENsb3VkMhIXCgZoZWFkZXIYASABKAsyBy5IZWFk",
          "ZXISHAoGcG9pbnRzGAIgAygLMgwuUG9pbnRYWVpSR0JiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::HeaderReflection.Descriptor, global::PointXYZRGBReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PointCloud2), global::PointCloud2.Parser, new[]{ "Header", "Points" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class PointCloud2 : pb::IMessage<PointCloud2> {
  private static readonly pb::MessageParser<PointCloud2> _parser = new pb::MessageParser<PointCloud2>(() => new PointCloud2());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PointCloud2> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PointCloud2Reflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PointCloud2() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PointCloud2(PointCloud2 other) : this() {
    Header = other.header_ != null ? other.Header.Clone() : null;
    points_ = other.points_.Clone();
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PointCloud2 Clone() {
    return new PointCloud2(this);
  }

  /// <summary>Field number for the "header" field.</summary>
  public const int HeaderFieldNumber = 1;
  private global::Header header_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Header Header {
    get { return header_; }
    set {
      header_ = value;
    }
  }

  /// <summary>Field number for the "points" field.</summary>
  public const int PointsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::PointXYZRGB> _repeated_points_codec
      = pb::FieldCodec.ForMessage(18, global::PointXYZRGB.Parser);
  private readonly pbc::RepeatedField<global::PointXYZRGB> points_ = new pbc::RepeatedField<global::PointXYZRGB>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::PointXYZRGB> Points {
    get { return points_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PointCloud2);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PointCloud2 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Header, other.Header)) return false;
    if(!points_.Equals(other.points_)) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (header_ != null) hash ^= Header.GetHashCode();
    hash ^= points_.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (header_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Header);
    }
    points_.WriteTo(output, _repeated_points_codec);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (header_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
    }
    size += points_.CalculateSize(_repeated_points_codec);
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PointCloud2 other) {
    if (other == null) {
      return;
    }
    if (other.header_ != null) {
      if (header_ == null) {
        header_ = new global::Header();
      }
      Header.MergeFrom(other.Header);
    }
    points_.Add(other.points_);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          if (header_ == null) {
            header_ = new global::Header();
          }
          input.ReadMessage(header_);
          break;
        }
        case 18: {
          points_.AddEntriesFrom(input, _repeated_points_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
