// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SEVData.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from SEVData.proto</summary>
public static partial class SEVDataReflection {

  #region Descriptor
  /// <summary>File descriptor for SEVData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SEVDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1TRVZEYXRhLnByb3RvGhFQb2ludENsb3VkMi5wcm90bxoLSW1hZ2UucHJv",
          "dG8iZQoHU0VWRGF0YRIaCgpsZWZ0X2ltYWdlGAEgASgLMgYuSW1hZ2USGwoL",
          "cmlnaHRfaW1hZ2UYAiABKAsyBi5JbWFnZRIhCgtwb2ludF9jbG91ZBgDIAEo",
          "CzIMLlBvaW50Q2xvdWQyYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::PointCloud2Reflection.Descriptor, global::ImageReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SEVData), global::SEVData.Parser, new[]{ "LeftImage", "RightImage", "PointCloud" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class SEVData : pb::IMessage<SEVData> {
  private static readonly pb::MessageParser<SEVData> _parser = new pb::MessageParser<SEVData>(() => new SEVData());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SEVData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SEVDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SEVData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SEVData(SEVData other) : this() {
    LeftImage = other.leftImage_ != null ? other.LeftImage.Clone() : null;
    RightImage = other.rightImage_ != null ? other.RightImage.Clone() : null;
    PointCloud = other.pointCloud_ != null ? other.PointCloud.Clone() : null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SEVData Clone() {
    return new SEVData(this);
  }

  /// <summary>Field number for the "left_image" field.</summary>
  public const int LeftImageFieldNumber = 1;
  private global::Image leftImage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Image LeftImage {
    get { return leftImage_; }
    set {
      leftImage_ = value;
    }
  }

  /// <summary>Field number for the "right_image" field.</summary>
  public const int RightImageFieldNumber = 2;
  private global::Image rightImage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Image RightImage {
    get { return rightImage_; }
    set {
      rightImage_ = value;
    }
  }

  /// <summary>Field number for the "point_cloud" field.</summary>
  public const int PointCloudFieldNumber = 3;
  private global::PointCloud2 pointCloud_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::PointCloud2 PointCloud {
    get { return pointCloud_; }
    set {
      pointCloud_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SEVData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SEVData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(LeftImage, other.LeftImage)) return false;
    if (!object.Equals(RightImage, other.RightImage)) return false;
    if (!object.Equals(PointCloud, other.PointCloud)) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (leftImage_ != null) hash ^= LeftImage.GetHashCode();
    if (rightImage_ != null) hash ^= RightImage.GetHashCode();
    if (pointCloud_ != null) hash ^= PointCloud.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (leftImage_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(LeftImage);
    }
    if (rightImage_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(RightImage);
    }
    if (pointCloud_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(PointCloud);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (leftImage_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeftImage);
    }
    if (rightImage_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(RightImage);
    }
    if (pointCloud_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(PointCloud);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SEVData other) {
    if (other == null) {
      return;
    }
    if (other.leftImage_ != null) {
      if (leftImage_ == null) {
        leftImage_ = new global::Image();
      }
      LeftImage.MergeFrom(other.LeftImage);
    }
    if (other.rightImage_ != null) {
      if (rightImage_ == null) {
        rightImage_ = new global::Image();
      }
      RightImage.MergeFrom(other.RightImage);
    }
    if (other.pointCloud_ != null) {
      if (pointCloud_ == null) {
        pointCloud_ = new global::PointCloud2();
      }
      PointCloud.MergeFrom(other.PointCloud);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          if (leftImage_ == null) {
            leftImage_ = new global::Image();
          }
          input.ReadMessage(leftImage_);
          break;
        }
        case 18: {
          if (rightImage_ == null) {
            rightImage_ = new global::Image();
          }
          input.ReadMessage(rightImage_);
          break;
        }
        case 26: {
          if (pointCloud_ == null) {
            pointCloud_ = new global::PointCloud2();
          }
          input.ReadMessage(pointCloud_);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
